version: "3.3"
services:
  algo_dev:
    container_name: deamov_algo_dev
    deploy:
      resources:
        reservations:
          devices:
          - driver: 'nvidia'
            count: 1
            capabilities: [gpu]
    build:
      context: ./
      dockerfile: ./docker_files/dev/Dockerfile
    ports:
      - 5055:22
    networks:
      - dev-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true

networks:
  dev-network:
    driver: bridge
