""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                                   Pluglist                                   "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
call plug#begin('~/.vim/plugged')
" Need attention

" System
Plug 'vim-scripts/LargeFile'                            " Fast Load for Large files
Plug 'michaeljsmith/vim-indent-object'                  " used for align
Plug 'terryma/vim-smooth-scroll'                        " smooth scroll
Plug 'wellle/targets.vim'                               " text objects
Plug 'ryanoasis/vim-devicons'                           " extensions for icons
Plug 'brglng/vim-im-select'                             " auto change input methods, needs `imselect` cmd
Plug 'unblevable/quick-scope'                           " Advance setting for f t search
Plug 'mbbill/undotree'                                  " history of the undo
if has('nvim')
  Plug 'Shougo/denite.nvim', { 'do': ':UpdateRemotePlugins' } " insteresting system
else
  Plug 'Shougo/denite.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
Plug 'Shougo/neoyank.vim'                                     " yank history using denite
Plug 'ncm2/float-preview.nvim'                                " showing doc with float windows not preview beside the functions
Plug 'junegunn/goyo.vim', {'for': ['markdown', 'tex']}
Plug 'junegunn/limelight.vim'

" Coding
Plug 'Shougo/deoplete.nvim', {'do': ':UpdateRemotePlugins'}
Plug 'davidhalter/jedi-vim'
Plug 'deoplete-plugins/deoplete-jedi'
Plug 'tbodt/deoplete-tabnine', { 'do': './install.sh' }
Plug 'w0rp/ale', {'for': ['cpp', 'python']}             " Syntax Check
Plug 'SirVer/ultisnips'                                 " snippets
Plug 'Duan-JM/vdeamov-snippets'
Plug 'tpope/vim-commentary'
Plug 'Raimondi/delimitMate'                             " Brackets Jump 智能补全括号和跳转
                                                        " 补全括号 shift+tab出来
Plug 'vim-scripts/matchit.zip'                          " %  g% [% ]% a%
Plug 'andymass/vim-matchup'                             " extence
Plug 'octol/vim-cpp-enhanced-highlight', {'for':['c', 'cpp']}
Plug 'godlygeek/tabular'                                " align text
Plug 'tpope/vim-surround'                               " change surroundings
                                                        " c[ange]s[old parttern] [new partten]
                                                        " ds[partten]
                                                        " ys(iww)[partten] / yss)
Plug 'tpope/vim-repeat'                                 " for use . to repeat for surround
Plug 'liuchengxu/vista.vim', {'for':['c', 'cpp', 'python']}                     " show params and functions

" Writing Blog
Plug 'voldikss/vim-translate-me', {'for':['markdown', 'tex']}
Plug 'rhysd/vim-grammarous', {'for': ['markdown', 'tex']}                       " grammarly checks
Plug 'hotoo/pangu.vim', {'for': ['markdown']}                                   "to make your document better
Plug 'godlygeek/tabular', {'for': ['markdown']}
Plug 'plasticboy/vim-markdown', {'for': ['markdown']}
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
Plug 'mzlogin/vim-markdown-toc', {'for': ['markdown']}
" :GenTocGFM/:GenTocRedcarpet
":UpdateToc 更新目录
Plug 'dhruvasagar/vim-table-mode', {'for': ['markdown']}
"<leader>tm to enable
"|| in the insert mode to create a horizontal line
"| match the | up row
"<leader>tdd to delete the row
"<leader>tdc to delete the coloum
"<leader>tt to change the exist text to format table
Plug 'xuhdev/vim-latex-live-preview', {'for': ['tex']}                          " Use when you work with cn
Plug 'lervag/vimtex', {'for': ['tex']}                                          " English is okay, fail with cn
Plug 'deoplete-plugins/deoplete-dictionary'


"FileManage
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-Plugin'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'mhinz/vim-startify'
Plug 'justinmk/vim-dirvish'
Plug 'kristijanhusak/vim-dirvish-git'


" Appearance
Plug 'itchyny/lightline.vim'
Plug 'flazz/vim-colorschemes'
Plug 'Yggdroot/indentLine'                                                      " Show indent line
Plug 'kshenoy/vim-signature'                                                    " Visible Mark
Plug 'luochen1990/rainbow'                                                      " multi color for Parentheses
Plug 'vim-scripts/peaksea'
Plug 'haishanh/night-owl.vim'
Plug 'nightsense/stellarized'
Plug 'nightsense/cosmic_latte'

" Github
Plug 'mattn/gist-vim'                                                           " :Gist -l/-ls :Gist -e (add gist name) -s (add description) -d (delete)
Plug 'mattn/webapi-vim'
Plug 'tpope/vim-fugitive'
Plug 'junegunn/gv.vim'                                                          " Rely on fugitive
Plug 'airblade/vim-gitgutter'                                                   " [c ]c jump to prev/next change [C ]C

" Search
Plug 'tpope/vim-abolish'                                                        "增强版的substitue
Plug 'Yggdroot/LeaderF'                                                         " Ultra search tools
                                                                                " <c-]> open in vertical 
Plug 'junegunn/vim-slash'                                                       " clean hightline after search
Plug 'brooth/far.vim'                                                           " search and replace
call plug#end()


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                                   Mappings                                   "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Caution: Mapping should place before PluginConfigure
let mapleader=' '

nmap . .`[
nmap <leader>w :w<CR>
nmap <leader>q :q<CR>


nnoremap <Leader>eg :e ++enc=gbk<CR>
nnoremap <Leader>eu :e ++enc=utf8<CR>

" nnoremap <leader>sl :set list!<CR>                    " quick config to see or not see special character  
nnoremap <leader>ll :set conceallevel=0<CR>             " quick change conceal mode

nnoremap <leader>ev :tabe $MYVIMRC<CR>                  " Quickly edit/reload the vimrc file

" show HEX and return
nnoremap <Leader>xd :%!xxd<CR>
nnoremap <Leader>xr :%!xxd -r<CR>

" Window control
nnoremap <leader>t :tabe<CR>                            " open a new tab
nnoremap <leader>v :vnew<CR>                            " close tab
nnoremap <leader>tq :tabclose<CR>
nnoremap <leader>tn :tabnext<CR>

" use ]+space create spaceline
nnoremap [<space>  :<c-u>put! =repeat(nr2char(10), v:count1)<cr>'[
nnoremap ]<space>  :<c-u>put =repeat(nr2char(10), v:count1)<cr>

" control term
" use c+[ to exit term to normal mode
tnoremap <c-[> <c-\><c-n>
nnoremap <leader>` :split \| term

" Use <C-L> to clear the highlighting of :set hlsearch
if maparg('<C-L>', 'n') ==# ''
    nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
endif

" map g* to *
nnoremap j gj
nnoremap k gk

" use <C-l> to correct spell while insert mode
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                               PluginConfigure                                "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" limelight.vim
" Color name (:help cterm-colors) or ANSI code
let g:limelight_conceal_ctermfg = 'gray'
let g:limelight_conceal_ctermfg = 240

" Color name (:help gui-colors) or RGB color
let g:limelight_conceal_guifg = 'DarkGray'
let g:limelight_conceal_guifg = '#777777'

" Default: 0.5
let g:limelight_default_coefficient = 0.7

" Number of preceding/following paragraphs to include (default: 0)
let g:limelight_paragraph_span = 3

" Beginning/end of paragraph
"   When there's no empty line between the paragraphs
"   and each paragraph starts with indentation
let g:limelight_bop = '^\s'
let g:limelight_eop = '\ze\n^\s'

" Highlighting priority (default: 10)
"   Set it to -1 not to overrule hlsearch
let g:limelight_priority = -1
autocmd! User GoyoEnter Limelight
autocmd! User GoyoLeave Limelight!

" Goyo
let g:goyo_linenr = 1

"ncm2/float_preview
function! DisableExtras()
  call nvim_win_set_option(g:float_preview#win, 'number', v:false)
  call nvim_win_set_option(g:float_preview#win, 'relativenumber', v:false)
  call nvim_win_set_option(g:float_preview#win, 'cursorline', v:false)
endfunction
autocmd User FloatPreviewWinOpen call DisableExtras()
let g:float_preview#docked = 0

" Define mappings
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
  \ denite#do_map('toggle_select').'j'
endfunction

" Neoyank
nnoremap <leader>y :Denite neoyank<cr>


" quick-scope
let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']
" Trigger a highlight in the appropriate direction when pressing these keys:
augroup qs_colors
  autocmd!
  autocmd ColorScheme * highlight QuickScopePrimary guifg='#afff5f' gui=underline ctermfg=155 cterm=underline
  autocmd ColorScheme * highlight QuickScopeSecondary guifg='#5fffff' gui=underline ctermfg=81 cterm=underline
augroup END


" Far
set regexpengine=1
nnoremap <space>s/ :F

" deoplete-tabnine
call deoplete#custom#var('tabnine', {
\ 'line_limit': 500,
\ 'max_num_results': 3,
\ })

" deoplete
let g:deoplete#enable_at_startup = 1

" deoplete-plugins/deoplete-jedi
let g:deoplete#sources#jedi#show_docstring = 0
call deoplete#custom#option({
\ 'deoplete-options-auto_complete': v:false,
\ 'deoplete-options-max_list': 100,
\ 'deoplete-options-skip_chars': ['(', ')', ':', ';']
\ })


" davidhalter/jedi-vim

let g:jedi#completions_enabled = 0
let g:jedi#auto_vim_configuration = 0
let g:jedi#goto_assignments_command = '<leader>g'   " dynamically done for
let g:jedi#goto_definitions_command = '<leader>jd'  " dynamically done for
let g:jedi#smart_auto_mappings = 1
let g:jedi#rename_command = ""
let g:jedi#auto_close_doc = 1

" deoplete-dictionary
setlocal dictionary+=/usr/share/dict/words
setlocal dictionary+=/usr/share/dict/american-english
" Remove this if you'd like to use fuzzy search
call deoplete#custom#source('dictionary', 'matchers', ['matcher_head'])
" If dictionary is already sorted, no need to sort it again.
call deoplete#custom#source('dictionary', 'sorters', [])
" Do not complete too short words
call deoplete#custom#source('dictionary', 'min_pattern_length', 4)

" translate-me
let g:vtm_default_mapping = 0
let g:vtm_target_lang = 'en' " default translate to english
let g:vtm_default_engines = ['ciba', 'youdao']
" let g:vtm_proxy_url = 'socks5://127.0.0.1:1080'

" <Leader>zt 翻译光标下的文本，在命令行回显
nmap <silent> <Leader>zt <Plug>Translate
vmap <silent> <Leader>zt <Plug>TranslateV
" Leader>zw 翻译光标下的文本，在窗口中显示
nmap <silent> <Leader>zw <Plug>TranslateW
vmap <silent> <Leader>zw <Plug>TranslateWV
" Leader>zr 替换光标下的文本为翻译内容
nmap <silent> <Leader>zr <Plug>TranslateR
vmap <silent> <Leader>zr <Plug>TranslateRV

"pathogen
execute pathogen#infect()

" vim-grammarous
let g:grammarous#hooks = {}
let g:grammarous#use_location_list = 1
function! g:grammarous#hooks.on_check(errs) abort
    nmap <buffer><C-n> <Plug>(grammarous-move-to-next-error)
    nmap <buffer><C-p> <Plug>(grammarous-move-to-previous-error)
    nmap <buffer><C-c><Plug>(grammarous-move-to-info-window)
endfunction

function! g:grammarous#hooks.on_reset(errs) abort
    nunmap <buffer><C-n> nunmap <buffer><C-p>
    nunmap <buffer><C-c>
endfunction

" rainbow
let g:rainbow_active = 1

""markdown-preview
"let g:mkdp_browser = 'Safari'

" vim-smooth-scroll
" Distance Duration Speed
noremap <silent> <c-u> :call smooth_scroll#up(&scroll, 8, 2)<CR>
noremap <silent> <c-d> :call smooth_scroll#down(&scroll, 8, 2)<CR>
noremap <silent> <c-b> :call smooth_scroll#up(&scroll*2, 8, 4)<CR>
noremap <silent> <c-f> :call smooth_scroll#down(&scroll*2, 8, 4)<CR>


" junegunn/vim-slash
noremap <plug>(slash-after) zz
if has('timers')
  " Blink 2 times with 50ms interval
  noremap <expr> <plug>(slash-after) slash#blink(2, 50)
endif

"vim-latex-live-preview
autocmd Filetype tex setl updatetime=1
let g:livepreview_previewer = 'open -a Preview'

"vimtex
let g:tex_flavor='latex'
let g:vimtex_view_method='skim'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'

"mhinz/vim-startify
let g:startify_list_order = [
            \ ['   Bookmarks'],     'bookmarks',
            \ ['   MRU'],           'files' ,
            \ ['   MRU '.getcwd()], 'dir',
            \ ['   Sessions'],      'sessions',
            \ ]
let g:startify_bookmarks = [
            \ '~/Desktop',
            \ '~/Documents/Coding/Test']
let g:startify_change_to_dir          = 0
let g:startify_enable_special         = 0
let g:startify_files_number           = 8
let g:startify_session_autoload       = 1
let g:startify_session_delete_buffers = 1
let g:startify_session_persistence    = 1
let g:startify_use_env                = 1

"scrooloose/nerdtree
nnoremap <leader>ne :NERDTreeFind<CR>
nnoremap <leader>nt :NERDTreeToggle<CR>
let g:NERDTreeShowLineNumbers=1
let NERDTreeAutoCenter=1
let g:NERDTreeChDirMode=2
let NERDTreeWinPos="left"
let g:nerdtree_tabs_open_on_console_startup=1
let g:NERDTreeShowBookmarks=1
let g:NERDTreeIgnore=['\.pyc','\~$','\.swp','\.DS_Store']

"vim-table-mode
let g:table_mode_corner = '|'
let g:table_mode_delimiter = ' '
let g:table_mdoe_verbose = 0
let g:table_mode_auto_align = 0
"autocmd FileType markdown TableModeEnable

"vim-markdown
let g:vim_markdown_math=1

"vim-markdown-toc
let g:vmt_auto_update_on_save=1 "update toc when save
let g:vmt_dont_insert_fence=0 "if equals to 1, can't update toc when save

"gist-vim
let github_user='Duan-JM'


"Yggdroot/indentLine
let g:indentLine_enabled=0
let g:indentLine_char_list = ['|', '¦', '┆', '┊']

""LeaderF
let g:Lf_ShortcutF = '<c-p>'
let g:Lf_ShortcutB = '<m-n>'
" let g:Lf_WindowPosition = 'popup'
" let g:Lf_PreviewInPopup = 1
" execute 'set <A-m>=\em,'
" execute 'set <A-b>=\eb'
" execute 'set <A-m>=\em'
noremap <c-n> :LeaderfMru<cr>
noremap <A-m> :LeaderfFunction!<cr>
noremap <A-b> :LeaderfBuffer<cr>
" noremap <A-m> :LeaderfTag<cr>
let g:Lf_StlSeparator = { 'left': '', 'right': '', 'font': '' }

let g:Lf_RootMarkers = ['.project', '.root', '.svn', '.git']
let g:Lf_WorkingDirectoryMode = 'Ac'
let g:Lf_WindowHeight = 0.30
let g:Lf_CacheDirectory = expand('~/.vim/cache')
let g:Lf_ShowRelativePath = 0
let g:Lf_HideHelp = 1
let g:Lf_StlColorscheme = 'powerline'
let g:Lf_PreviewResult = {'Function':0, 'BufTag':0}


" vista.vim
" How each level is indented and what to prepend.
" This could make the display more compact or more spacious.
" e.g., more compact: ["▸ ", ""]
let g:vista_icon_indent = ["╰─▸ ", "├─▸ "]
let g:vista#renderer#enable_icon = 1

" The default icons can't be suitable for all the filetypes, you can extend it as you wish.
let g:vista#renderer#icons = {
\   "function": "\uf794",
\   "variable": "\uf71b",
\  }


"LightLine
let g:lightline = {
      \ 'colorscheme': 'seoul256',
      \ 'active': {
      \   'left': [ 
      \     [ 'mode', 'paste' ],
      \     [ 'filename', 'modified' ],
      \     [ 'gitbranch', 'git_changes' ],
      \     [ 'vista' ],
      \   ],
      \   'right': [
      \     ['lineinfo'],
      \     ['percent'],
      \     ['readonly', 'linter_warnings', 'linter_errors', 'linter_ok'],
      \   ]
      \ },
      \ 'component_function': {
      \   'match_count': 'MatchCountStatusline',
      \   'gitbranch': 'fugitive#head',
      \   'git_changes': 'LightLineChanges',
      \ },
      \ 'component_expand': {
      \     'linter_warnings': 'LightlineLinterWarnings',
      \     'linter_errors':   'LightlineLinterErrors',
      \     'linter_ok':       'LightlineLinterOK',
      \   },
      \ 'component_type': {
      \   'readonly':        'error',
      \   'linter_warnings': 'warning',
      \   'linter_errors':   'error'
      \ },
      \ 'separator': {
      \   'left': '',
      \   'right': ''
      \ },
      \ 'enable': {
      \   'statusline': 1,
      \   'tabline': 0
      \ }
    \ }

function! LightLineChanges()
  let l:hunkSummary = v:null
  if exists('*GitGutterGetHunkSummary')
    let l:hunkSummary = GitGutterGetHunkSummary()
  elseif exists('g:loaded_signify') && sy#buffer_is_active()
    let l:hunkSummary = sy#repo#get_stats()
  endif
  if (empty(l:hunkSummary))
    return ''
  else
    let [ l:added, l:modified, l:removed ] = l:hunkSummary
    let l:total = (l:added + l:modified + l:removed)
    let l:output = ''
    if (l:added != 0)
      let l:output .= printf('+%d ', l:added)
    endif
    if (l:modified != 0)
      let l:output .= printf('~%d ', l:modified)
    endif
    if (l:removed != 0)
      let l:output .= printf('-%d ', l:removed)
    endif
    return '(' . l:output . ')'
  endif
endfunction

function! LightlineLinterWarnings() abort
  if (&readonly)
    return ''
  endif
  let l:counts = ale#statusline#Count(bufnr(''))
  let l:all_errors = l:counts.error + l:counts.style_error
  let l:all_non_errors = l:counts.total - l:all_errors
  return l:all_non_errors == 0 ? '' : printf('%d ▲', l:all_non_errors)
endfunction

function! LightlineLinterErrors() abort
  if (&readonly)
    return ''
  endif
  let l:counts = ale#statusline#Count(bufnr(''))
  let l:all_errors = l:counts.error + l:counts.style_error
  let l:all_non_errors = l:counts.total - l:all_errors
  return l:all_errors == 0 ? '' : printf('%d ✗', l:all_errors)
endfunction

function! LightlineLinterOK() abort
  if (&readonly)
    return ''
  endif
  let l:counts = ale#statusline#Count(bufnr(''))
  let l:all_errors = l:counts.error + l:counts.style_error
  let l:all_non_errors = l:counts.total - l:all_errors
  return l:counts.total == 0 ? '✓' : ''
endfunction

augroup ale_stuff
  au!
  autocmd User ALELint call s:MaybeUpdateLightline()
augroup END

function! s:MaybeUpdateLightline()
  " Update and show lightline but only if it's visible (e.g., not in Goyo)
  if exists('#lightline')
    call lightline#update()
  end
endfunction



"SirVer/ultisnips
"customize python and keymapping
"ref:https://gist.github.com/lencioni/dff45cd3d1f0e5e23fe6
"ref:https://stackoverflow.com/questions/14896327/ultisnips-and-youcompleteme
let g:UltiSnipsUsePythonVersion    = 3
let g:UltiSnipsExpandTrigger       = "<tab>"
let g:UltiSnipsJumpForwardTrigger  = "<c-j>"
let g:UltiSnipsJumpBackwardTrigger = "<c-k>"
let g:snips_author = "Duan-JM"
let g:snips_email = "vincent.duan95@outlook.com"
let g:snips_github = "https://github.com/Duan-JM"


"w0rp/ale
let g:ale_linters_explicit = 1
let g:ale_completion_delay = 500
let g:ale_echo_delay = 20
let g:ale_lint_delay = 500
let g:ale_echo_msg_format = '[%linter%] %code: %%s'
let g:ale_lint_on_text_changed = 'normal'
let g:ale_lint_on_insert_leave = 1
let g:ale_c_gcc_options = '-Wall -O2 -std=c99'
let g:ale_cpp_gcc_options = '-Wall -O2 -std=c++14'
let g:ale_c_cppcheck_options = ''
let g:ale_cpp_cppcheck_options = ''
let g:ale_sign_eror = 'E'
let g:ale_sign_warning = 'W'
let g:ale_linters = {
\   'python': ['pylint'],
\   'tex': ['lacheck'],
\   'swift': ['swiftlint'],
\   'markdown': ['markdownlint'],
\   'cpp': ['gcc', 'cpplint'],
\   'c': ['gcc', 'cpplint'],
\   'java': ['javac','google-java-format'],
\}
let g:ale_go_langserver_executable = 'gopls'
let g:ale_fixers = {
\   '*': ['remove_trailing_lines','trim_whitespace' ],
\   'python': ['autopep8']
\}
"let g:ale_fix_on_save = 1 "auto Sava
"Use :ALEFix to fix
let g:ale_list_window_size = 5


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                                Basic Settings                                "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set nocompatible                                                        " not compatible for vi
set nospell                                                             " close spell examine
set number                                                              " show number 
set relativenumber                                                      "show relative line number
set hlsearch                                                            " Highlight the matching part
set incsearch                                                           " Shows the match while typing
set ignorecase
set smartcase
set showmatch                                                           " Show matching brackets/parenthesis
set encoding=utf-8                                                      " configure the encoding
set fileencodings=utf-8,gbk,utf-16le,cp1252,iso-8859-15,ucs-bom
set fileformats=unix,dos,mac
set linespace=0                                                         " No extra spaces between rows
set confirm                                                             " Confirm before vim exit
set nobackup
set noswapfile
set lazyredraw                                                          " don't update the display while executing macros
set backspace=eol,start,indent                                          " use backspace for delete space line
set ruler                                                               " show the cursor's position
set nomodeline                                                          " disable mode lines (security measure)
set noshowmode                                                          " do not show Insert, We already have it in lightline
set mouse=a                                                             " allow mouse select and etc operation
set autoindent                                                          " config the indent
set smartindent
set smarttab
set copyindent
set tabstop=2  softtabstop=2 shiftwidth=2 expandtab textwidth=79
set history=1000                                                        " save 1000 cmd
set timeoutlen=500                                                      " give u 500 time to react for cmd
set list                                                                " show the special character
set guioptions=e                                                        "only show guitablabel
set autoread
set autowrite
set autowriteall                                                        " Auto-write all file changes
set iskeyword-=_,.,=,-,:,
" set guifont=Source\ Code\ Pro\ for\ Powerline:h16
set switchbuf=useopen                                                   " reveal already opened files from the
                                                                        " quickfix window instead of opening new buffers
set wildmenu
" set cursorcolumn                                                        " highlight column
" set cursorline                                                          " highlight row
if has('nvim')                                                          " Use floating windows to complete the commond, only neovim support
  set wildoptions=pum
  set termguicolors                                                     " With out this settings, transparable float-win will not work normally
  set pumblend=30                                                       " Let floatingwindow to be transparable
  set winblend=9
else
  set wildmode=list:longest,full                                        " Set list to show completeopt, however it will lead to disfunc for floating windows
endif
set nowrap                                                              " Do not wrap long lines
set whichwrap=b,s,h,l,<,>,>h,[,]                                        " Backspace and cursor keys wrap too
set t_Co=256                                                            " number of colors
"set autochdir                                                          "disable for leadf
set laststatus=2                                                        " always show statusline
set showtabline=2                                                       " always show tabline
set hidden
set display+=lastline
set noerrorbells novisualbell t_vb=                                     " cancel the annoying bell
set belloff=all
set showcmd                                                             " Show partial commands in status line and
" Selected characters/lines in visual mode
set viewoptions=folds,options,cursor,unix,slash                         " Better Unix / Windows compatibility
set virtualedit=onemore                                                 " used with caution of breaking plugins
set completeopt=menuone,noinsert,menu,preview,longest
set completeopt-=preview                                                " avoid preview windows for function docs
set tags=./tags;/,~/.vimtags
set dictionary+=/usr/share/dict/words                                   " autocompletion with dictionary help
set dictionary+=~/.vim/dict/
set statusline+=%*
set statusline+=%#warningmsg#
set shortmess+=filmnrxoOtT                                              " Abbrev. of messages (avoids 'hit enter')

set undofile                                                            " enable undo after close the file
set undodir=$HOME/.vim/undo
set undolevels=1000
set undoreload=10000

set splitbelow
set splitright

filetype on
filetype plugin indent on

if has('syntax')
    syntax enable
endif

if has('clipboard')
    if has('unnamedplus')                                               " When possible use + register for copy-paste
        set clipboard=unnamed,unnamedplus
    else                                                                " On mac and Windows, use * register for copy-paste
        set clipboard=unnamed
    endif
endif


set wildignore=*.o,*~,*.pyc,*.swp,*.bak,*.class,*.DS_Store              " vim will ignore them
if has('win16') || has('win32')
    set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store
else
    set wildignore+=.git\*,.hg\*,.svn\*
endif

if !&scrolloff                                                          " Minimum lines to keep above and below cursor
    set scrolloff=1
endif

if !&sidescrolloff
    set scrolloff=5
endif


set colorcolumn=+1                                                      " color the 81 column for warning
" let &colorcolumn=join(range(81,999),',')
" let &colorcolumn='80,'.join(range(120,999),',')

" fold config
" foldmethod [diff, expr, indent, manual, marker, syntax]
" diff show the diff between unfold and fold
" expr use `foldexpr` to config fold logic
" indent fold base on indent
" manual use zf zF or :Fold to fold, zfa(,
"                     :mkview to save 
"                     :loadview to reload
" mark ....
" syntax
set foldmethod=manual
set foldlevel=99
set foldlevelstart=99

" nnoremap <space> za
" vnoremap <space> zf 

let gitroot = substitute(system('git rev-parse --show-toplevel'),'[\n\r]', '', 'g')                          " Make tags placed in .git/tags file available in all levels of a repository
if gitroot != ''
    let &tags = &tags . ',' . gitroot . '/.git/tags'
endif

" set colorful cursors
set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50
  \,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor
  \,sm:block-blinkwait175-blinkoff150-blinkon175

" wrap config (not recommend
" formation options
" default is tcq 
" t: 根据 textwidth 自动折行
" c: 在（程序源代码中的）注释中自动折行，插入合适的注释起始字符
" r: 插入模式下在注释中键入回车时，插入合适的注释起始字符
" q: 允许使用"gq"命令对注释进行格式化；
" n: 识别编号列表，编号行的下一行的缩进由数字后的空白决定（与“2”冲突，需要“autoindent”）；
" 2: 使用一段的第二行的缩进来格式化文本；
" l: 在当前行长度超过 textwidth 时，不自动重新格式化；
" m: 在多字节字符处可以折行，对中文特别有效（否则只在空白字符处折行）；
" M: 在拼接两行时（重新格式化，或者是手工使用“J”命令），如果前一行的结尾或后一行的开头是多字节字符，则不插入空格，非常适合中文
" 
" set textwidth=80 "最大字符长度
" set formatoptions+=t
set formatoptions-=t "disable wrap
" set formatoptions-=l " wrap long lines
" if v:version > 703 || v:version == 703 && has('patch541')
"     set formatoptions+=j " Delete comment chars when join comment lines
" endif
" set wrapmargin=2 " 2 chars wrap margin from the right window border, hard wrap


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                                 Functions                                  "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"let W Wq wQ not be error
command! -bar -nargs=* -complete=file -range=% -bang W         <line1>,<line2>write<bang> <args>
command! -bar -nargs=* -complete=file -range=% -bang Wq        <line1>,<line2>wq<bang> <args>
command! -bar -nargs=* -complete=file -range=% -bang WQ        <line1>,<line2>wq<bang> <args>
command! -bar -nargs=* -complete=file -range=% -bang We        <line1>,<line2>w<bang> | e <args>
command! -bar -nargs=* -complete=file          -bang E         edit<bang> <args>
command! -bar                                  -bang Q         quit<bang>

" Set tabstop, softtabstop and shiftwidth to the same value
command! -nargs=1 Rename let tpname = expand('%:t') | saveas <args> | edit <args> | call delete(expand(tpname))
command! -nargs=* Stab call Stab()

"普通模式和可视模式下&都代表着重复上一次搜索操作，同时保持上一次的搜索域
nnoremap & :&&<CR>
xnoremap & :&&<CR>

" 可视模式下，用 * 和 # 搜索选中文本
xnoremap * :<C-u>call <SID>VSetSearch()<CR>/<C-r>=@/<CR><CR>
xnoremap # :<C-u>call <SID>VSetSearch()<CR>?<C-r>=@/<CR><CR>

function! s:VSetSearch()
    let temp = @s
    norm! gv"sy
    let @/ = '\V' . substitute(escape(@s, '/\'), '\n', '\\n', 'g')
    let @s = temp
endfunction

function! Stab()
    "设置缩进
    let l:tabstop = 1 * input('set tabstop = softtabstop = shiftwidth = ')
    if l:tabstop > 0
        let &l:sts = l:tabstop
        let &l:ts = l:tabstop
        let &l:sw = l:tabstop
    endif
    call SummarizeTabs()
endfunction

function! SummarizeTabs()
    "查看当前的缩进情况
    try
        echohl ModeMsg
        echon 'tabstop='.&l:ts
        echon ' shiftwidth='.&l:sw
        echon ' softtabstop='.&l:sts
        if &l:et
            echon ' expandtab'
        else
            echon ' noexpandtab'
        endif
    finally
        echohl None
    endtry
endfunction

function! GuiTabLabel()
    let label = ''
    let bufnrlist = tabpagebuflist(v:lnum)
    " Add '+' if one of the buffers in the tab page is modified
    for bufnr in bufnrlist
        if getbufvar(bufnr, "&modified")
            let label = '+'
            break
        endif
    endfor
    " Append the tab number
    let label .= v:lnum.': '
    " Append the buffer name
    let name = bufname(bufnrlist[tabpagewinnr(v:lnum) - 1])
    if name == ''
        " give a name to no-name documents
        if &buftype=='quickfix'
            let name = '[Quickfix List]'
        else
            let name = '[No Name]'
        endif
    else
        " get only the file name
        let name = fnamemodify(name,":t")
    endif
    let label .= name
    " Append the number of windows in the tab page
    let wincount = tabpagewinnr(v:lnum, '$')
    return label . '  [' . wincount . ']'
endfunction

function! SetTabLabel()
    set guitablabel=%{GuiTabLabel()}
endfunction

" http://vimdoc.sourceforge.net/htmldoc/gui.html
"echom "May The FORCE be with U!"
if exists('+showtabline')
    function! MyTabLine()
        let s = ''
        let t = tabpagenr()
        let i = 1
        while i <= tabpagenr('$')
            let buflist = tabpagebuflist(i)
            let winnr = tabpagewinnr(i)
            let s .= '%' . i . 'T'
            let s .= (i == t ? '%1*' : '%2*')
            let s .= ' '
            let s .= i . ':'
            let s .= ' %*'
            let s .= (i == t ? '%#TabLineSel#' : '%#TabLine#')
            let file = bufname(buflist[winnr - 1])
            let file = fnamemodify(file, ':p:t')
            if file == ''
                let file = '[No Name]'
            endif
            let s .= file
            let i = i + 1
        endwhile
        let s .= '%T%#TabLineFill#%='
        let s .= (tabpagenr('$') > 1 ? '%999XX' : 'X')
        return s
    endfunction
    set stal=2
    set tabline=%!MyTabLine()
endif

"http://vim.wikia.com/wiki/Show_tab_number_in_your_tab_line
" set up tab tooltips with every buffer name
function! GuiTabToolTip()
    let tip = ''
    let bufnrlist = tabpagebuflist(v:lnum)
    for bufnr in bufnrlist
        " separate buffer entries
        if tip != ''
            let tip .= " \n "
        endif
        " Add name of buffer
        let name = bufname(bufnr)
        " add modified/modifiable flags
        if getbufvar(bufnr, "&modified")
            let tip .= ' [+]'
        endif
    endfor
    return tip
endfunction
set guitabtooltip=%{GuiTabToolTip()}

" url:http://vimcasts.org/episodes/tidying-whitespace/
function! Preserve(command)
    " Preparation: save last search, and cursor position.
    let _s=@/
    let l = line('.')
    let c = col('.')
    " Do the business:
    execute a:command
    " Clean up: restore previous search history, and cursor position
    let @/=_s
    call cursor(l, c)
endfunction

" clean space in the end of line
nnoremap _$ :call Preserve("%s/\\s\\+$//e")<CR>
" clean extra whitespace in whole docs
nnoremap _= :call Preserve("normal gg=G")<CR>

"Allow to toggle background
function!  ToggleBG()
    let s:tbg = &background
    " Inversion
    if s:tbg == 'light'
        set background=dark
    else
        set background=light
    endif
endfunction

" set background transparable
func! s:transparent_background()
    highlight Normal guibg=None ctermbg=None
    highlight NonText guibg=None ctermbg=None
endf
autocmd ColorScheme * call s:transparent_background()

" set background is dark at the startup
set background=dark
noremap <leader>bg :call ToggleBG()<CR>

"CompileConfig
"按F5运行python"
map <F10> :w<CR> :call RunPython()<CR>
function! RunPython()
    let mp = &makeprg
    let ef = &errorformat
    let exeFile = expand("%:t")
    setlocal makeprg=python\ -u
    set efm=%C\ %.%#,%A\ \ File\ \"%f\"\\,\ line\ %l%.%#,%Z%[%^\ ]%\\@=%m
    silent make %
    copen
    let &makeprg = mp
    let &errorformat = ef
endfunction

nnoremap <leader>r :call CompileRun()<CR>
func! CompileRun()
    exec "w"
    if &filetype == 'c'
        exec "!gcc % -o %<"
        exec "!time ./%<"

    elseif &filetype == 'cpp'
        exec "!g++ % -o %<"
        exec "!time ./%<"

    elseif &filetype == 'java'
        exec "!clear"
        exec "!javac %"
        exec "!time java %<"

    elseif &filetype == 'sh'
        exec "!clear"
        exec "!time bash %"

    elseif &filetype == 'python'
        exec ":split | term python3 %"

    elseif &filetype == 'html'
        exec "!open -a Safari % &"

    elseif &filetype == 'go'
        exec "!clear"
        exec "!go build %<"
        exec "!time go run %"

    elseif &filetype == 'markdown'
        exec "!clear"
        exec "!open -a Marked %"

    elseif &filetype == 'tex'
        exec "silent! :VimtexCompile"
    endif
endfunc

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                             FileType Conifgure                             "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
autocmd! BufNewFile,BufRead *.markdown *.md set filetype=markdown
autocmd! BufNewFile,BufRead *.ts set filetype=typescript
autocmd! BufNewFile,BufRead *.json set filetype=json
autocmd! BufNewFile,BufRead,BufReadPost *.snippets set filetype=snippets
autocmd! BufNewFile,BufRead *.vs,*.fs set filetype=glsl
autocmd! BufNewFile,BufRead *.swift set filetype=swift
autocmd! BufNewFile,BufRead *.vm *.xtpl *.ejs set filetype=html
autocmd! BufNewFile,BufRead *.html.twig set filetype=html.twig
autocmd! BufNewFile,BufRead *.conf set filetype=config
autocmd! BufRead,BufNewFile *.scss set filetype=scss.css
autocmd! BufNewFile,BufRead *.coffee set filetype=coffee
autocmd! BufNewFile,BufRead *.rss *.atom setfiletype xml
autocmd! BufNewFile,BufRead *.vm set ft=velocity
autocmd! BufNewFile,BufRead *.mako set ft=mako
autocmd! BufNewFile,BufRead *.tex set filetype=tex
autocmd! BufNewFile,BufRead *.bat
            \ if getline(1) =~ '--\*-Perl-\*--' | setf perl | endif


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                                    Themes                                    "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" should be placed before AutoCMD, or some color configure will not avaliable
" colorscheme Tomorrow-Night
" colorscheme PaperColor
" colorscheme mayansmoke
" colorscheme anderson
" colorscheme wombat256
" colorscheme space-vim-dark
" colorscheme gruvbox
" colorscheme Atelier_CaveDark
" colorscheme vividchalk
" colorscheme night-owl
let g:onedark_termcolors=256
colorscheme onedark
" colorscheme stellarized
" colorscheme cosmic_latte
" colorscheme peaksea

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                                  AutoCMD                                   "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Check for vim-plug if not exist download it
if filereadable('~/.vim/autoload/plug.vim')
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  augroup vimplug
    au!
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
  augroup END
endif

" config for all file type =====>
" Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
            \ if &filetype != "gitcommit" && line("'\"") > 0 && line("'\"") <= line("$") |
            \   exe "normal! g`\"" |
            \ endif

"https://superuser.com/questions/195022/vim-how-to-synchronize-nerdtree-with-current-opened-tab-file-path
if expand("%:p")
    autocmd BufEnter * lcd %:p:h
endif
"http://inlehmansterms.net/2014/09/04/sane-vim-working-directories/
"http://vim.wikia.com/wiki/Set_working_directory_to_the_current_file
autocmd BufEnter * silent! lcd %:p:h
autocmd BufEnter * if expand("%:p:h") !~ '^/tmp' | silent! lcd %:p:h | endif
let s:default_path = escape(&path, '\ ') " store default value of 'path'


" Automatically open and close the popup menu / preview window
autocmd CursorMovedI,InsertLeave * if pumvisible() == 0|silent! pclose|endif


autocmd FocusGained, BufEnter * :silent! !
autocmd WinEnter call SetTabLabel()                                         " show tabline
autocmd BufEnter call SetTabLabel()
autocmd VimEnter * :call SetTabLabel()

autocmd! BufWritePost .vimrc source ~/.vimrc                                " source vimrc immediately


autocmd! FileType gitcommit autocmd! BufEnter COMMIT_EDITMSG
            \ call setpos('.', [0, 1, 1, 0])                                " set it to the first line when editing a git commit message

" config for tex
autocmd! FileType tex set spell | 
            \ set spelllang=en_us | 
            \ set wrap | 
            \ set whichwrap=b,s,h,l,<,>,>h,[,]                                                            " Do not wrap long lines



" config for python
" Let external space be red for python
autocmd! FileType python syn keyword pythonDecorator True None False self
highlight BadWhitespace guifg=gray guibg=red ctermfg=gray ctermbg=red
autocmd BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/


" gnuplot syntax highlighting
autocmd BufNewFile,BufRead *.plt,.gnuplot setf gnuplot
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
autocmd FileType ruby set dictionary+=~/.vim/dict/ruby.dict
autocmd FileType javascript set dictionary+=$HOME/.vim/dict/node.dict

" configure for term to exit directly
" autocmd TermClose * call feedkeys("i")

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                                 Custom Reg                                  "
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" add space between current character
let @s='i la '
"}
