services:
  nginx:
    platform: linux/amd64
    image: nginx:alpine
    container_name: nacos-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
      - "8848:8848"
    depends_on:
      - nacos
    restart: always
    networks:
      - nacos-net
  nacos:
    platform: linux/amd64
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos
    env_file:
      - ./env/nacos.env
    environment:
      - JVM_XMS=256m
      - JVM_XMX=256m
      - JVM_XMN=128m
    volumes:
      - ./nacos-logs/:/home/nacos/logs
    ports:
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - nacos-net
  mysql:
    platform: linux/amd64
    container_name: mysql
    build:
      context: .
      dockerfile: ./image/mysql/8/Dockerfile
    image: nacos/mysql:8.0.30
    env_file:
      - ./env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: always
    networks:
      - nacos-net
networks:
  nacos-net:
    driver: bridge
